name: compose-validate
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mostrar versión de Docker/Compose
        run: |
          docker --version
          docker compose version
      - name: Validar docker-compose.yml
        run: docker compose -f docker-compose.yml config
