name: link-check
on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/workflows/link-check.yml'
  schedule:
    - cron: '0 7 * * 1'   # Lunes 07:00 UTC (semanal)
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
