name: link-check
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose --exclude "http://localhost" README.md
